### ISSUE TITLE
.unwrap() tracker

### ISSUE THREAD

**Issue by Dustin-Ray** [spaceandtimelabs/sxt-proof-of-sql#135]
Several unwraps occur outside of test code in this repo that may cause a panic under certain conditions. Any options or errors should handled or mapped fallibly. Here is a running list of known unwraps so far:

Accessors for query commitment:
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/base/commitment/query_commitments.rs

- [x] max_integer_type_function: should be resolved in #152 
https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/database/column.rs#L317-L318

owned arrow conversions for decimal:
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/database/owned_and_arrow_conversions.rs#L76

receive challenge function
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/proof/transcript_core.rs#L22

multiple unwraps in transcript protocol.rs
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/base/proof/transcript_protocol.rs

montscalar from bigint
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/scalar/mont_scalar.rs#L131
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/scalar/mont_scalar.rs#L278

batch inverse
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/base/slice_ops/batch_inverse.rs#L69

Quite a few in dory commitment helper:
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/proof_primitive/dory/dory_commitment_helper_cpu.rs

several in dory messages:
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/proof_primitive/dory/dory_messages.rs

several in parings.rs
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/proof_primitive/dory/pairings.rs

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/parse/filter_exec_builder.rs#L64

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs#L78

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs#L82

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/postprocessing/group_by_postprocessing.rs#L132

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/proof/proof_builder.rs#L177

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs#L139

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/proof/verifiable_query_result.rs#L142

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/proof/verification_builder.rs#L156

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql/src/sql/proof_exprs/numerical_util.rs#L45

several in sign_expr:
- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/main/crates/proof-of-sql/src/sql/proof_exprs/sign_expr.rs

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql-parser/src/intermediate_ast.rs#L226

- [ ] https://github.com/spaceandtimelabs/sxt-proof-of-sql/blob/2a197527501a7d2602b30587e750b98816537f9f/crates/proof-of-sql-parser/src/select_statement.rs#L84

**Comment by nanshuren** [comment]
您好，邮件已收到！

**Comment by JayWhite2357** [comment]
The true resolution to this problem is adding the `clippy:unwrap_used` lint to the CI.
We can handle the existing `unwraps` similar to how we handle existing missing docs in https://github.com/spaceandtimelabs/sxt-proof-of-sql/pull/156.
